const att = {
  type: "tuple",
  components: [
    { name: "handle", type: "bytes32" },
    { name: "value", type: "bytes32" },
  ],
} as const;

const tableTuple = {
  name: "v",
  type: "tuple",
  components: [
    { name: "phase_", type: "uint8" },
    { name: "p0", type: "address" },
    { name: "p1", type: "address" },
    { name: "turn_", type: "uint8" },
    { name: "toPlay", type: "address" },
    { name: "top", type: "uint16" },
    { name: "shape", type: "uint8" },
    { name: "pick", type: "uint8" },
    { name: "pickKind", type: "uint8" },
    { name: "ready", type: "bool" },
    { name: "winner_", type: "address" },
    { name: "hand0", type: "uint8" },
    { name: "hand1", type: "uint8" },
    { name: "marketLeft", type: "uint16" },
    { name: "solo", type: "bool" },
    { name: "botPending_", type: "bool" },
  ],
} as const;

export const whotAbi = [
  {
    type: "function",
    name: "dealFee",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextTableId",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "openTable",
    inputs: [],
    outputs: [{ name: "id", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "openSolo",
    inputs: [],
    outputs: [{ name: "id", type: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "botThink",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "botDump",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "handIndex", type: "uint8" },
      { name: "att", ...att },
      { name: "sigs", type: "bytes[]" },
      { name: "nextShape", type: "uint8" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "botMarket",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "lockBot",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "att", ...att },
      { name: "sigs", type: "bytes[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "botPackedOf",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cancelTable",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "joinAndDeal",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "lockOpener",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "att", ...att },
      { name: "sigs", type: "bytes[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "play",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "handIndex", type: "uint8" },
      { name: "att", ...att },
      { name: "sigs", type: "bytes[]" },
      { name: "nextShape", type: "uint8" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "goMarket",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getHandHandles",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "player", type: "address" },
    ],
    outputs: [{ name: "out", type: "bytes32[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "openerOf",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "mySeat",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [{ name: "", type: "int8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "table",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [tableTuple],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "stats",
    inputs: [{ name: "", type: "address" }],
    outputs: [
      { name: "wins", type: "uint32" },
      { name: "losses", type: "uint32" },
      { name: "played", type: "uint32" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ladderLength",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getLadder",
    inputs: [
      { name: "offset", type: "uint256" },
      { name: "limit", type: "uint256" },
    ],
    outputs: [
      { name: "players", type: "address[]" },
      { name: "wins", type: "uint32[]" },
      { name: "losses", type: "uint32[]" },
      { name: "played", type: "uint32[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "TableOpened",
    inputs: [
      { name: "host", type: "address", indexed: true },
      { name: "id", type: "uint256", indexed: true },
    ],
  },
  {
    type: "event",
    name: "TableCancelled",
    inputs: [{ name: "id", type: "uint256", indexed: true }],
  },
  {
    type: "event",
    name: "Dealt",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "a", type: "address", indexed: false },
      { name: "b", type: "address", indexed: false },
      { name: "openerHandle", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "OpenerSet",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "card", type: "uint16", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CardPlayed",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "player", type: "address", indexed: true },
      { name: "card", type: "uint16", indexed: false },
      { name: "calledShape", type: "uint8", indexed: false },
      { name: "call", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Market",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "player", type: "address", indexed: true },
      { name: "n", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CheckUp",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "winner", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "SoloOpened",
    inputs: [
      { name: "player", type: "address", indexed: true },
      { name: "id", type: "uint256", indexed: true },
    ],
  },
  {
    type: "event",
    name: "BotMove",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "packedHandle", type: "bytes32", indexed: false },
    ],
  },
] as const;
